import { Typography } from "@mui/material"

function Main() {
  return (
    <>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
     <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    <p>'MAIN'</p>
    </>
  )
}
export default Main